Hopefully finalized the main script

diff --git a/scripts/build-capstan-mpm-packages b/scripts/build-capstan-mpm-packages
--- a/scripts/build-capstan-mpm-packages
+++ b/scripts/build-capstan-mpm-packages
@@ -1,5 +1,47 @@
 #!/bin/bash
 
+# This script is an enhanced version of the original scripts found at 
+# https://github.com/wkozaczuk/docker_osv_builder/tree/master/packages/scripts
+# and intended to automate process of building capstan MPM packages 
+# (https://github.com/cloudius-systems/capstan/blob/master/Documentation/ApplicationManagement.md#package-management),
+#
+# Capstan package is a compressed tarball with an extension *.mpm containing application specific binaries plus
+# optional meta/run.yaml specifying command line to run it on OSv. Library packages typically do not have run.yaml.
+# For package to have any meaning it also needs an external YAML descriptor with extension .yaml. As an example
+# here is a package mpm file and its descriptor found in local repository:
+#
+#  $HOME/.capstan/packages/osv.iperf3.mpm
+#  $HOME/.capstan/packages/osv.iperf3.yaml
+#
+# Please note that mpm package files built by this script contain an internal copy of the descriptor inside of the tarball. 
+#
+# Packages can be pulled from a remote repository like OSv git releases or S3 based one or can
+# be built and published locally. This script builds and copies packages to the local capstan repository
+# at $HOME/.capstan/packages.
+#
+# The script accepts two types of the arguments - name of an OSv app or module found under OSv
+# apps or modules subdirectory or name of predefined set of standard packages.
+#
+# If an app or module name passed in, the script does following:
+# 1. Calls ./script/build with appropriate arguments to build and export corresponding
+#    OSv app or module files.
+# 2. Creates a temporary package build directory where package files and descriptors will be placed.
+# 3. Attempts to locate and read package.yaml under apps/<name>/mpm or modules/<name>/mpm
+#    directory to identify package name, title, version and names of any required packages.
+#    If package.yaml not found it assumes defaults for those value.
+# 4. Calls 'capstan package init' with values identified in the step above to create
+#    package descriptor - meta/package.yaml - in the temp directory.
+# 5. Generates meta/run.yaml if the build/release/cmdline is not empty.
+# 6. Copies files exported by ./scripts/build to the temporary directory.
+# 7. Lastly calls 'capstan package build' to build an mpm package that gets
+#    copied along with the descriptor to $HOME/.capstan/packages.
+#
+if [ "$1" == "" ]
+then
+  echo "Usage: build-capstan-mpm-packages <OSv_app_or_module>|<package_group>"
+  exit 1
+fi
+
 OSV_ROOT=$(realpath "$(dirname $0)/..")
 OSV_BUILD=$OSV_ROOT/build/release
 
@@ -14,6 +56,8 @@ PACKAGES=/tmp/capstan-packages
 CAPSTAN=capstan
 CAPSTAN_LOCAL_REPO=$HOME/.capstan
 OUTPUT=$CAPSTAN_LOCAL_REPO/packages
+
+ASK=0
 
 clean_osv() {
   cd "$OSV_ROOT" && ./scripts/build clean
@@ -30,6 +74,14 @@ build_osv_image() {
   echo "-------------------------------------"
 
   cd "$OSV_ROOT" && ./scripts/build -j4 image="$image" export="$export_mode" usrskel="$usrskel"
+
+  RET_VAL=$?
+  if [[ "$RET_VAL" -ne 0 ]]; then
+    echo "-------------------------------------"
+    echo " !!! Failed to build OSv image $image -> aborting !!!"
+    echo "-------------------------------------"
+    exit 1
+  fi
 
   echo "-------------------------------------"
   echo "- Built OSv image $image             "
@@ -130,6 +182,16 @@ build_mpm() {
   set_package_command_line $app_or_module_name
   build_package $app_or_module_name
 
+  if [[ $ASK -ne 0 ]]; then
+    read -p "Continue building next package [y/N]? :" -n 1 -t 30 -s
+    echo
+    if [[ ! "$REPLY" =~ ^[Yy]$ ]]; then
+      echo "Aborted."
+      rm -rf $package_dir
+      exit 1
+    fi
+  fi
+
   rm -rf $package_dir
 }
 
@@ -188,8 +250,7 @@ build_unit_tests_package() {
 }
 
 build_http_server_tests_package() {
-  build_osv_image "josvsym,httpserver-jolokia-plugin,httpserver-jvm-plugin" selected none
-  #build_osv_image "josvsym,httpserver-jolokia-plugin,httpserver-jvm-plugin,certs" selected none
+  build_osv_image "josvsym,httpserver-jolokia-plugin,httpserver-jvm-plugin,certs" selected none
   build_mpm "httpserver-api-tests"
 }
 
@@ -217,6 +278,7 @@ build_openjdk11-zulu-package() {
 #----------------
 
 build_kernel_and_standard_osv_apps() {
+  ASK=1
   build_osv_image_loader_and_bootstrap_package
 
   build_httpserver_api_package
@@ -225,25 +287,31 @@ build_kernel_and_standard_osv_apps() {
   build_cli_package
 
   build_run_java_package
+  ASK=0
   build_and_publish_mpm run-go
 }
 
 build_java_jdk_packages() {
+  ASK=1
   build_openjdk8-zulu-compact3-with-java-beans_package
+  ASK=0
   build_openjdk11-zulu-package
 }
 
 build_java_example_apps() {
+  ASK=1
   build_and_publish_mpm jetty
   build_and_publish_mpm elasticsearch
   build_and_publish_mpm apache-derby
   build_and_publish_mpm spring-boot-example
   build_and_publish_mpm apache-kafka native
   build_and_publish_mpm apache-kafka zookeeper
+  ASK=0
   build_and_publish_mpm vertx native
 }
 
 build_other_example_apps() {
+  ASK=1
   build_and_publish_mpm lighttpd
   PYTHON_VERSION=2 build_and_publish_mpm python-from-host
   PYTHON_VERSION=3 build_and_publish_mpm python-from-host
@@ -256,51 +324,51 @@ build_other_example_apps() {
   build_and_publish_mpm memcached
   build_and_publish_mpm mysql
   build_and_publish_mpm lua-hello-from-host
+  ASK=0
   build_and_publish_mpm ffmpeg
 
   #Add core utils
 }
 
-# ...
-# Copy rust,vertx and node apps used for perm tests
-
 # ---- TESTS 
 build_test_apps() {
+  ASK=1
+  build_unit_tests_package
+  build_http_server_tests_package
+
   build_and_publish_mpm rust-example
   build_and_publish_mpm rust-httpserver
+
   build_and_publish_mpm golang-example
   build_and_publish_mpm golang-httpserver
   build_and_publish_mpm golang-pie-example
   build_and_publish_mpm golang-pie-httpserver
+
   build_and_publish_mpm graalvm-example
   build_and_publish_mpm graalvm-httpserver
   build_and_publish_mpm graalvm-netty-plot
 
-  #jvm (java):
-  #  jetty (ab)
-  #  tomcat (ab)
-  #  spring boot (ab)
-  #  elasticsearch (ab)
-  #  apache-derby (only start)
-  #node express
-  #python 2/3
-  #lua
-  #ffmpeg
-  #mysql (bench)
-  #redis
-  #iperf3
-  #netperf
-  #stream
-  #
-  # cli
-  # httpserver-api REST test - exists test
-  #   make check in
-  #later JMV
-  #specjvm
-  #tomcat-benchamrk
+  ASK=0
+  build_and_publish_mpm node-express-example
 }
 
-#build_and_publish_mpm $1
-
-#build_unit_tests_package
-build_http_server_tests_package
+case "$1" in
+  kernel)
+    echo "Building kernel and standard apps ..."
+    build_kernel_and_standard_osv_apps;;
+  jdk)
+    echo "Building Java 8 and 11 JREs ..."
+    build_java_jdk_packages;;
+  java_examples)
+    echo "Building Java examples ..."
+    build_java_example_apps;;
+  other_examples)
+    echo "Building other examples ..."
+    build_other_example_apps;;
+  tests)
+    echo "Building test apps ..."
+    build_test_apps;;
+  *)
+    echo "Building package $1 ..."
+    build_and_publish_mpm $1 $2
+esac
